### ISSUE TITLE
接口串行、并行的用法

### ISSUE THREAD

**Issue by twlk27** [FE-star/homework3#4]
想请教老师，当接口串行、并行的时候，是怎么调用homework3这个lib的？

1. 接口串行（类似`Promise.then`）的调用，是写成下面这样吗？

```javascript

const api1 = request('http://xxx/1')
const api2 = request('http://xxx/2')

api1.get()
	.done((res, flag)=>{
		api2.get()
		.done((res2, flag)=>{
			// blablabla with res&res2
		})
	})

```

2. 然后并行（类似`Promise.all`）的情况，怎么调用呢？

3. 最后问个和这个作业无关的，`Promise.race`的使用场景是啥？

**Comment by miniflycn** [comment]
接口串行我没有设计，并行看看Defer的代码，里面new的时候可以传入多个Defer

`Promise.race`说真，从来没用过……
